package com.infraspine.callsync.data.remote

import com.google.gson.JsonElement
import okhttp3.MultipartBody
import okhttp3.RequestBody
import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.Multipart
import retrofit2.http.POST
import retrofit2.http.Part
import retrofit2.http.Query

/**
 * CRM upload contract. Backend integration is pending — this interface defines the
 * agreed shape so the rest of the app can be built and tested against it now
 * (see [com.infraspine.callsync.data.remote.DummyCrmUploader] for the stand-in
 * used while [dummyTestMode][com.infraspine.callsync.data.prefs.SecureSettingsStore.dummyTestMode]
 * is enabled).
 *
 * Endpoint: POST /api/crm/call-recordings/upload
 * Body: multipart/form-data generated by Retrofit/OkHttp. Do not add a manual
 * Content-Type header here; OkHttp must include its generated boundary.
 * Auth: Bearer access token, attached via an OkHttp interceptor and never logged.
 */
interface CrmApiService {

    @POST("api/auth/login")
    suspend fun login(
        @Body request: LoginRequest
    ): Response<LoginResponse>

    @Multipart
    @POST("api/crm/call-recordings/upload")
    suspend fun uploadCallRecording(
        @Part file: MultipartBody.Part,
        @Part("phoneNumber") phoneNumber: RequestBody?,
        @Part("callStartedAt") callStartedAt: RequestBody?,
        @Part("durationSeconds") durationSeconds: RequestBody?,
        @Part("callType") callType: RequestBody?,
        @Part("deviceId") deviceId: RequestBody,
        @Part("originalFileName") originalFileName: RequestBody
    ): Response<UploadResponse>

    @POST("api/crm/call-logs/sync")
    suspend fun syncCallLogs(
        @Body request: CallLogsSyncRequest
    ): Response<CallLogsSyncResponse>

    @GET("api/crm/call-logs/sync-state")
    suspend fun getCallLogSyncState(
        @Query("deviceId") deviceId: String
    ): Response<CallLogSyncStateResponse>

    @GET("api/crm/call-logs/sync/status")
    suspend fun getCallLogSyncStatus(
        @Query("deviceId") deviceId: String
    ): Response<CallLogSyncStatusResponse>

    /**
     * Returns which of the given call logs already exist on the server, so the
     * app can skip re-uploading them. A 404/501 response means the backend
     * doesn't support this endpoint yet — callers should treat all records as
     * missing (i.e. fall back to current upload-everything behavior).
     */
    @POST("api/crm/call-logs/check-existing")
    suspend fun checkExistingCallLogs(
        @Body request: CallLogExistingCheckRequest
    ): Response<CallLogExistingCheckResponse>

    /**
     * Returns which of the given recordings already exist on the server, so the
     * app can skip re-uploading them. A 404/501 response means the backend
     * doesn't support this endpoint yet — callers should treat all records as
     * missing (i.e. fall back to current upload-everything behavior).
     */
    @POST("api/crm/call-recordings/check-existing")
    suspend fun checkExistingRecordings(
        @Body request: RecordingExistingCheckRequest
    ): Response<RecordingExistingCheckResponse>
}

/**
 * Expected JSON shape of a successful upload response. Field names are a best-guess
 * placeholder contract; align with the actual CRM API once it is available.
 */
data class UploadResponse(
    val success: Boolean? = null,
    val recordingId: String? = null,
    val message: String? = null
)

data class LoginRequest(
    val email: String,
    val password: String
)

data class LoginResponse(
    val accessToken: String? = null,
    val token: String? = null,
    val userId: String? = null,
    val name: String? = null,
    val email: String? = null,
    val user: LoginUser? = null,
    val message: String? = null
)

data class LoginUser(
    val id: String? = null,
    val userId: String? = null,
    val name: String? = null,
    val email: String? = null
)

data class CallLogsSyncRequest(
    val logs: List<CallLogSyncItem>
)

data class CallLogSyncItem(
    val externalCallId: String,
    val phoneNumber: String,
    val callStartedAt: String,
    val durationSeconds: Long,
    val callType: String,
    val deviceId: String
)

data class CallLogsSyncResponse(
    val success: Boolean? = null,
    val uploaded: Int? = null,
    val skipped: Int? = null,
    val insertedCount: Int? = null,
    val duplicateCount: Int? = null,
    val latestServerCallStartedAt: JsonElement? = null,
    val latestServerCallLogId: JsonElement? = null,
    val message: String? = null
)

data class CallLogSyncStateResponse(
    val latestCallStartedAt: JsonElement? = null,
    val latestAndroidCallLogId: JsonElement? = null,
    val totalLogs: Int? = null,
    val message: String? = null
)

data class CallLogSyncStatusResponse(
    val latestExternalCallId: JsonElement? = null,
    val latestCallStartedAt: JsonElement? = null,
    val latestSyncedAt: JsonElement? = null,
    val totalLogs: Int? = null,
    val instanceId: String? = null,
    val message: String? = null
)
